image: sbtscala/scala-sbt:amazoncorretto-al2023-17.0.13_1.10.7_3.6.2

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"
  _JAVA_OPTIONS: "-Djava.awt.headless=true"

cache:
  paths:
    - sbt-cache/.ivy/cache
    - sbt-cache/.boot
    - sbt-cache/.sbtboot
    - target/

stages:
  - compile
  - test
  - package

before_script:
  # Install dependencies for ScalaFX in headless environment
  - apt-get update -y && apt-get install -y xvfb libxtst6 libxrender1

compile:
  stage: compile
  script:
    - sbt compile
  artifacts:
    paths:
      - target/

test:
  stage: test
  dependencies:
    - compile
  before_script:
    - apt-get update && apt-get install -y xvfb
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - export DISPLAY=:99
  script:
    - sbt test
  artifacts:
    reports:
      junit: target/test-reports/*.xml
    when: always

package:
  stage: package
  script:
    - sbt assembly
  dependencies:
    - test
  artifacts:
    paths:
      - target/scala-*/scalaboids_2.13-*.jar
  only:
    - main